name: stowage_plan
description: Command line application for testing logic of interaction with stowage plan.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  collection: ^1.19.0
